[workspace]
members = [
    "crates/compiler-common",
    "crates/compiler-frontend",
    "crates/compiler-ir",
    "crates/compiler-backend",
    "crates/compiler-cli",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Samii"]
